/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 1

enum ts_symbol_identifiers {
  sym_string = 1,
  anon_sym_lockfile = 2,
  aux_sym_lockfile_directive_token1 = 3,
  anon_sym_klar = 4,
  anon_sym_package = 5,
  anon_sym_from = 6,
  anon_sym_npm = 7,
  anon_sym_local = 8,
  anon_sym_workspace = 9,
  anon_sym_git = 10,
  anon_sym_branch = 11,
  anon_sym_dependency = 12,
  anon_sym_for = 13,
  anon_sym_dev = 14,
  anon_sym_integrity = 15,
  anon_sym_path = 16,
  anon_sym_registry = 17,
  anon_sym_subpath = 18,
  anon_sym_tag = 19,
  anon_sym_url = 20,
  anon_sym_POUND = 21,
  aux_sym_comment_token1 = 22,
  sym_version = 23,
  sym_commit_number = 24,
  sym_source_file = 25,
  sym_lockfile_directive = 26,
  sym_klar_directive = 27,
  sym_full_package_directive = 28,
  sym_package_directive = 29,
  sym_package_header = 30,
  sym_source = 31,
  sym_package_subdirective = 32,
  sym_package_branch_directive = 33,
  sym_package_dependency_directive = 34,
  sym_package_for_dev_directive = 35,
  sym_package_for_workspace_directive = 36,
  sym_package_integrity_directive = 37,
  sym_package_path_directive = 38,
  sym_package_registry_directive = 39,
  sym_package_subpath_directive = 40,
  sym_package_tag_directive = 41,
  sym_package_url_directive = 42,
  sym_comment = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_full_package_directive_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_string] = "string",
  [anon_sym_lockfile] = "lockfile",
  [aux_sym_lockfile_directive_token1] = "lockfile_directive_token1",
  [anon_sym_klar] = "klar",
  [anon_sym_package] = "package",
  [anon_sym_from] = "from",
  [anon_sym_npm] = "npm",
  [anon_sym_local] = "local",
  [anon_sym_workspace] = "workspace",
  [anon_sym_git] = "git",
  [anon_sym_branch] = "branch",
  [anon_sym_dependency] = "dependency",
  [anon_sym_for] = "for",
  [anon_sym_dev] = "dev",
  [anon_sym_integrity] = "integrity",
  [anon_sym_path] = "path",
  [anon_sym_registry] = "registry",
  [anon_sym_subpath] = "subpath",
  [anon_sym_tag] = "tag",
  [anon_sym_url] = "url",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_version] = "version",
  [sym_commit_number] = "commit_number",
  [sym_source_file] = "source_file",
  [sym_lockfile_directive] = "lockfile_directive",
  [sym_klar_directive] = "klar_directive",
  [sym_full_package_directive] = "full_package_directive",
  [sym_package_directive] = "package_directive",
  [sym_package_header] = "package_header",
  [sym_source] = "source",
  [sym_package_subdirective] = "package_subdirective",
  [sym_package_branch_directive] = "package_branch_directive",
  [sym_package_dependency_directive] = "package_dependency_directive",
  [sym_package_for_dev_directive] = "package_for_dev_directive",
  [sym_package_for_workspace_directive] = "package_for_workspace_directive",
  [sym_package_integrity_directive] = "package_integrity_directive",
  [sym_package_path_directive] = "package_path_directive",
  [sym_package_registry_directive] = "package_registry_directive",
  [sym_package_subpath_directive] = "package_subpath_directive",
  [sym_package_tag_directive] = "package_tag_directive",
  [sym_package_url_directive] = "package_url_directive",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_full_package_directive_repeat1] = "full_package_directive_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_string] = sym_string,
  [anon_sym_lockfile] = anon_sym_lockfile,
  [aux_sym_lockfile_directive_token1] = aux_sym_lockfile_directive_token1,
  [anon_sym_klar] = anon_sym_klar,
  [anon_sym_package] = anon_sym_package,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_npm] = anon_sym_npm,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_workspace] = anon_sym_workspace,
  [anon_sym_git] = anon_sym_git,
  [anon_sym_branch] = anon_sym_branch,
  [anon_sym_dependency] = anon_sym_dependency,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_dev] = anon_sym_dev,
  [anon_sym_integrity] = anon_sym_integrity,
  [anon_sym_path] = anon_sym_path,
  [anon_sym_registry] = anon_sym_registry,
  [anon_sym_subpath] = anon_sym_subpath,
  [anon_sym_tag] = anon_sym_tag,
  [anon_sym_url] = anon_sym_url,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_version] = sym_version,
  [sym_commit_number] = sym_commit_number,
  [sym_source_file] = sym_source_file,
  [sym_lockfile_directive] = sym_lockfile_directive,
  [sym_klar_directive] = sym_klar_directive,
  [sym_full_package_directive] = sym_full_package_directive,
  [sym_package_directive] = sym_package_directive,
  [sym_package_header] = sym_package_header,
  [sym_source] = sym_source,
  [sym_package_subdirective] = sym_package_subdirective,
  [sym_package_branch_directive] = sym_package_branch_directive,
  [sym_package_dependency_directive] = sym_package_dependency_directive,
  [sym_package_for_dev_directive] = sym_package_for_dev_directive,
  [sym_package_for_workspace_directive] = sym_package_for_workspace_directive,
  [sym_package_integrity_directive] = sym_package_integrity_directive,
  [sym_package_path_directive] = sym_package_path_directive,
  [sym_package_registry_directive] = sym_package_registry_directive,
  [sym_package_subpath_directive] = sym_package_subpath_directive,
  [sym_package_tag_directive] = sym_package_tag_directive,
  [sym_package_url_directive] = sym_package_url_directive,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_full_package_directive_repeat1] = aux_sym_full_package_directive_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_lockfile] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_lockfile_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_klar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_package] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_npm] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_workspace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_git] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_branch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dependency] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dev] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_integrity] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_path] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_registry] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_subpath] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tag] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_url] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [sym_commit_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_lockfile_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_klar_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_full_package_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_package_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_package_header] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_package_subdirective] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_package_branch_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_package_dependency_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_package_for_dev_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_package_for_workspace_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_package_integrity_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_package_path_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_package_registry_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_package_subpath_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_package_tag_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_package_url_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_full_package_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_commit = 1,
  field_name = 2,
  field_source = 3,
  field_version = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_commit] = "commit",
  [field_name] = "name",
  [field_source] = "source",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_source, 3},
    {field_version, 1},
  [3] =
    {field_commit, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_package_subdirective,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_package_subdirective] = {.index = 0, .length = 10},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_package_branch_directive,
    sym_package_dependency_directive,
    sym_package_for_dev_directive,
    sym_package_for_workspace_directive,
    sym_package_integrity_directive,
    sym_package_path_directive,
    sym_package_registry_directive,
    sym_package_subpath_directive,
    sym_package_tag_directive,
    sym_package_url_directive,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == 'v') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == 'v') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '#') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_lockfile_directive_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_lockfile_directive_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_lockfile_directive_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(12);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_string);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_string);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_string);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_commit_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'b', 1,
        'd', 2,
        'f', 3,
        'g', 4,
        'i', 5,
        'k', 6,
        'l', 7,
        'n', 8,
        'p', 9,
        'r', 10,
        's', 11,
        't', 12,
        'u', 13,
        'v', 14,
        'w', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(18);
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'p') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(33);
      if (lookahead == 'v') ADVANCE(34);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(40);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(41);
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(42);
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 26:
      if (lookahead == 'g') ADVANCE(44);
      END_STATE();
    case 27:
      if (lookahead == 'b') ADVANCE(45);
      END_STATE();
    case 28:
      if (lookahead == 'g') ADVANCE(46);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_version);
      if (lookahead == '.') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(48);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_dev);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 36:
      if (lookahead == 'm') ADVANCE(51);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_git);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 40:
      if (lookahead == 'a') ADVANCE(54);
      if (lookahead == 'k') ADVANCE(55);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_npm);
      END_STATE();
    case 42:
      if (lookahead == 'k') ADVANCE(56);
      END_STATE();
    case 43:
      if (lookahead == 'h') ADVANCE(57);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(58);
      END_STATE();
    case 45:
      if (lookahead == 'p') ADVANCE(59);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_tag);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_url);
      END_STATE();
    case 48:
      if (lookahead == 'k') ADVANCE(60);
      END_STATE();
    case 49:
      if (lookahead == 'c') ADVANCE(61);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 52:
      if (lookahead == 'g') ADVANCE(63);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_klar);
      END_STATE();
    case 54:
      if (lookahead == 'l') ADVANCE(64);
      END_STATE();
    case 55:
      if (lookahead == 'f') ADVANCE(65);
      END_STATE();
    case 56:
      if (lookahead == 'a') ADVANCE(66);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_path);
      END_STATE();
    case 58:
      if (lookahead == 's') ADVANCE(67);
      END_STATE();
    case 59:
      if (lookahead == 'a') ADVANCE(68);
      END_STATE();
    case 60:
      if (lookahead == 's') ADVANCE(69);
      END_STATE();
    case 61:
      if (lookahead == 'h') ADVANCE(70);
      END_STATE();
    case 62:
      if (lookahead == 'd') ADVANCE(71);
      END_STATE();
    case 63:
      if (lookahead == 'r') ADVANCE(72);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 65:
      if (lookahead == 'i') ADVANCE(73);
      END_STATE();
    case 66:
      if (lookahead == 'g') ADVANCE(74);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(76);
      END_STATE();
    case 69:
      if (lookahead == 'p') ADVANCE(77);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_branch);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 72:
      if (lookahead == 'i') ADVANCE(79);
      END_STATE();
    case 73:
      if (lookahead == 'l') ADVANCE(80);
      END_STATE();
    case 74:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 75:
      if (lookahead == 'r') ADVANCE(82);
      END_STATE();
    case 76:
      if (lookahead == 'h') ADVANCE(83);
      END_STATE();
    case 77:
      if (lookahead == 'a') ADVANCE(84);
      END_STATE();
    case 78:
      if (lookahead == 'n') ADVANCE(85);
      END_STATE();
    case 79:
      if (lookahead == 't') ADVANCE(86);
      END_STATE();
    case 80:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_package);
      END_STATE();
    case 82:
      if (lookahead == 'y') ADVANCE(88);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_subpath);
      END_STATE();
    case 84:
      if (lookahead == 'c') ADVANCE(89);
      END_STATE();
    case 85:
      if (lookahead == 'c') ADVANCE(90);
      END_STATE();
    case 86:
      if (lookahead == 'y') ADVANCE(91);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_lockfile);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_registry);
      END_STATE();
    case 89:
      if (lookahead == 'e') ADVANCE(92);
      END_STATE();
    case 90:
      if (lookahead == 'y') ADVANCE(93);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_integrity);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_workspace);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_dependency);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 11},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_lockfile] = ACTIONS(1),
    [aux_sym_lockfile_directive_token1] = ACTIONS(1),
    [anon_sym_klar] = ACTIONS(1),
    [anon_sym_package] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_npm] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_workspace] = ACTIONS(1),
    [anon_sym_git] = ACTIONS(1),
    [anon_sym_branch] = ACTIONS(1),
    [anon_sym_dependency] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_dev] = ACTIONS(1),
    [anon_sym_integrity] = ACTIONS(1),
    [anon_sym_path] = ACTIONS(1),
    [anon_sym_registry] = ACTIONS(1),
    [anon_sym_subpath] = ACTIONS(1),
    [anon_sym_tag] = ACTIONS(1),
    [anon_sym_url] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
    [sym_version] = ACTIONS(1),
    [sym_commit_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(32),
    [sym_lockfile_directive] = STATE(25),
    [sym_comment] = STATE(1),
    [anon_sym_lockfile] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_package_subdirective] = STATE(5),
    [sym_package_branch_directive] = STATE(6),
    [sym_package_dependency_directive] = STATE(6),
    [sym_package_for_dev_directive] = STATE(6),
    [sym_package_for_workspace_directive] = STATE(6),
    [sym_package_integrity_directive] = STATE(6),
    [sym_package_path_directive] = STATE(6),
    [sym_package_registry_directive] = STATE(6),
    [sym_package_subpath_directive] = STATE(6),
    [sym_package_tag_directive] = STATE(6),
    [sym_package_url_directive] = STATE(6),
    [sym_comment] = STATE(2),
    [aux_sym_full_package_directive_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_package] = ACTIONS(7),
    [anon_sym_branch] = ACTIONS(9),
    [anon_sym_dependency] = ACTIONS(11),
    [anon_sym_for] = ACTIONS(13),
    [anon_sym_integrity] = ACTIONS(15),
    [anon_sym_path] = ACTIONS(17),
    [anon_sym_registry] = ACTIONS(19),
    [anon_sym_subpath] = ACTIONS(21),
    [anon_sym_tag] = ACTIONS(23),
    [anon_sym_url] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_package_subdirective] = STATE(5),
    [sym_package_branch_directive] = STATE(6),
    [sym_package_dependency_directive] = STATE(6),
    [sym_package_for_dev_directive] = STATE(6),
    [sym_package_for_workspace_directive] = STATE(6),
    [sym_package_integrity_directive] = STATE(6),
    [sym_package_path_directive] = STATE(6),
    [sym_package_registry_directive] = STATE(6),
    [sym_package_subpath_directive] = STATE(6),
    [sym_package_tag_directive] = STATE(6),
    [sym_package_url_directive] = STATE(6),
    [sym_comment] = STATE(3),
    [aux_sym_full_package_directive_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_package] = ACTIONS(27),
    [anon_sym_branch] = ACTIONS(29),
    [anon_sym_dependency] = ACTIONS(32),
    [anon_sym_for] = ACTIONS(35),
    [anon_sym_integrity] = ACTIONS(38),
    [anon_sym_path] = ACTIONS(41),
    [anon_sym_registry] = ACTIONS(44),
    [anon_sym_subpath] = ACTIONS(47),
    [anon_sym_tag] = ACTIONS(50),
    [anon_sym_url] = ACTIONS(53),
    [anon_sym_POUND] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_branch,
    ACTIONS(11), 1,
      anon_sym_dependency,
    ACTIONS(13), 1,
      anon_sym_for,
    ACTIONS(15), 1,
      anon_sym_integrity,
    ACTIONS(17), 1,
      anon_sym_path,
    ACTIONS(19), 1,
      anon_sym_registry,
    ACTIONS(21), 1,
      anon_sym_subpath,
    ACTIONS(23), 1,
      anon_sym_tag,
    ACTIONS(25), 1,
      anon_sym_url,
    STATE(2), 1,
      aux_sym_full_package_directive_repeat1,
    STATE(4), 1,
      sym_comment,
    STATE(5), 1,
      sym_package_subdirective,
    STATE(6), 10,
      sym_package_branch_directive,
      sym_package_dependency_directive,
      sym_package_for_dev_directive,
      sym_package_for_workspace_directive,
      sym_package_integrity_directive,
      sym_package_path_directive,
      sym_package_registry_directive,
      sym_package_subpath_directive,
      sym_package_tag_directive,
      sym_package_url_directive,
  [52] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(5), 1,
      sym_comment,
    ACTIONS(56), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [72] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(6), 1,
      sym_comment,
    ACTIONS(58), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [92] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(7), 1,
      sym_comment,
    ACTIONS(60), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [112] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(8), 1,
      sym_comment,
    ACTIONS(62), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [132] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(9), 1,
      sym_comment,
    ACTIONS(64), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [152] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(10), 1,
      sym_comment,
    ACTIONS(66), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [172] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(11), 1,
      sym_comment,
    ACTIONS(68), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [192] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(12), 1,
      sym_comment,
    ACTIONS(70), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [212] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(13), 1,
      sym_comment,
    ACTIONS(72), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [232] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(14), 1,
      sym_comment,
    ACTIONS(74), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [252] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(15), 1,
      sym_comment,
    ACTIONS(76), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [272] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(16), 1,
      sym_comment,
    ACTIONS(78), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [292] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(17), 1,
      sym_comment,
    ACTIONS(80), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [312] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(18), 1,
      sym_comment,
    ACTIONS(82), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [332] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(19), 1,
      sym_comment,
    ACTIONS(84), 11,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [352] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(20), 1,
      sym_comment,
    ACTIONS(86), 9,
      anon_sym_branch,
      anon_sym_dependency,
      anon_sym_for,
      anon_sym_integrity,
      anon_sym_path,
      anon_sym_registry,
      anon_sym_subpath,
      anon_sym_tag,
      anon_sym_url,
  [370] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(90), 1,
      anon_sym_git,
    STATE(18), 1,
      sym_source,
    STATE(21), 1,
      sym_comment,
    ACTIONS(88), 3,
      anon_sym_npm,
      anon_sym_local,
      anon_sym_workspace,
  [388] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 1,
      anon_sym_package,
    STATE(4), 1,
      sym_package_directive,
    STATE(22), 1,
      sym_comment,
    STATE(24), 1,
      aux_sym_source_file_repeat1,
    STATE(27), 1,
      sym_full_package_directive,
  [410] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 1,
      anon_sym_package,
    STATE(4), 1,
      sym_package_directive,
    STATE(27), 1,
      sym_full_package_directive,
    STATE(23), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
  [430] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(94), 1,
      anon_sym_package,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_package_directive,
    STATE(23), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 1,
      sym_comment,
    STATE(27), 1,
      sym_full_package_directive,
  [452] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(103), 1,
      anon_sym_klar,
    STATE(22), 1,
      sym_klar_directive,
    STATE(25), 1,
      sym_comment,
  [465] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(105), 1,
      sym_string,
    STATE(20), 1,
      sym_package_header,
    STATE(26), 1,
      sym_comment,
  [478] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(27), 1,
      sym_comment,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      anon_sym_package,
  [489] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(105), 1,
      sym_string,
    STATE(9), 1,
      sym_package_header,
    STATE(28), 1,
      sym_comment,
  [502] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(29), 1,
      sym_comment,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      anon_sym_package,
  [513] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(111), 1,
      anon_sym_workspace,
    ACTIONS(113), 1,
      anon_sym_dev,
    STATE(30), 1,
      sym_comment,
  [526] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(115), 1,
      sym_string,
    STATE(31), 1,
      sym_comment,
  [536] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    STATE(32), 1,
      sym_comment,
  [546] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(119), 1,
      sym_string,
    STATE(33), 1,
      sym_comment,
  [556] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(121), 1,
      anon_sym_from,
    STATE(34), 1,
      sym_comment,
  [566] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(123), 1,
      sym_string,
    STATE(35), 1,
      sym_comment,
  [576] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(125), 1,
      sym_version,
    STATE(36), 1,
      sym_comment,
  [586] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(127), 1,
      anon_sym_klar,
    STATE(37), 1,
      sym_comment,
  [596] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(129), 1,
      sym_string,
    STATE(38), 1,
      sym_comment,
  [606] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(131), 1,
      sym_string,
    STATE(39), 1,
      sym_comment,
  [616] = 3,
    ACTIONS(133), 1,
      anon_sym_POUND,
    ACTIONS(135), 1,
      aux_sym_comment_token1,
    STATE(40), 1,
      sym_comment,
  [626] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(137), 1,
      sym_version,
    STATE(41), 1,
      sym_comment,
  [636] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(139), 1,
      aux_sym_lockfile_directive_token1,
    STATE(42), 1,
      sym_comment,
  [646] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(141), 1,
      sym_string,
    STATE(43), 1,
      sym_comment,
  [656] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(143), 1,
      sym_commit_number,
    STATE(44), 1,
      sym_comment,
  [666] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      sym_string,
    STATE(45), 1,
      sym_comment,
  [676] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(147), 1,
      sym_string,
    STATE(46), 1,
      sym_comment,
  [686] = 1,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 52,
  [SMALL_STATE(6)] = 72,
  [SMALL_STATE(7)] = 92,
  [SMALL_STATE(8)] = 112,
  [SMALL_STATE(9)] = 132,
  [SMALL_STATE(10)] = 152,
  [SMALL_STATE(11)] = 172,
  [SMALL_STATE(12)] = 192,
  [SMALL_STATE(13)] = 212,
  [SMALL_STATE(14)] = 232,
  [SMALL_STATE(15)] = 252,
  [SMALL_STATE(16)] = 272,
  [SMALL_STATE(17)] = 292,
  [SMALL_STATE(18)] = 312,
  [SMALL_STATE(19)] = 332,
  [SMALL_STATE(20)] = 352,
  [SMALL_STATE(21)] = 370,
  [SMALL_STATE(22)] = 388,
  [SMALL_STATE(23)] = 410,
  [SMALL_STATE(24)] = 430,
  [SMALL_STATE(25)] = 452,
  [SMALL_STATE(26)] = 465,
  [SMALL_STATE(27)] = 478,
  [SMALL_STATE(28)] = 489,
  [SMALL_STATE(29)] = 502,
  [SMALL_STATE(30)] = 513,
  [SMALL_STATE(31)] = 526,
  [SMALL_STATE(32)] = 536,
  [SMALL_STATE(33)] = 546,
  [SMALL_STATE(34)] = 556,
  [SMALL_STATE(35)] = 566,
  [SMALL_STATE(36)] = 576,
  [SMALL_STATE(37)] = 586,
  [SMALL_STATE(38)] = 596,
  [SMALL_STATE(39)] = 606,
  [SMALL_STATE(40)] = 616,
  [SMALL_STATE(41)] = 626,
  [SMALL_STATE(42)] = 636,
  [SMALL_STATE(43)] = 646,
  [SMALL_STATE(44)] = 656,
  [SMALL_STATE(45)] = 666,
  [SMALL_STATE(46)] = 676,
  [SMALL_STATE(47)] = 686,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_package_directive, 2, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_full_package_directive_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_full_package_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_full_package_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_full_package_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_full_package_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_full_package_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_full_package_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_full_package_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_full_package_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_full_package_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_full_package_directive_repeat1, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_subdirective, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_branch_directive, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_for_dev_directive, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_dependency_directive, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_integrity_directive, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_path_directive, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_tag_directive, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_registry_directive, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_url_directive, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_subpath_directive, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_for_workspace_directive, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_header, 4, 0, 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 2, 0, 2),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_directive, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_klar_directive, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [117] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lockfile_directive, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_glaslock(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_string,
    .primary_state_ids = ts_primary_state_ids,
    .name = "glaslock",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
